version: '3.0'
services:  
  rag-speech-chat:
    container_name: rag-speech-chat
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # api keys read from .env file in the root directory
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      LLM: ${LLM}
    restart: unless-stopped
    ports:
      - 8000:8000

