version: '3.0'
services:  
  rag-speech-chat:
    container_name: rag-speech-chat
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # api keys read from .env file in the root directory
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      RETURN_SOURCE_DOCUMENTS: ${RETURN_SOURCE_DOCUMENTS}
      VECTOR_COUNT: ${VECTOR_COUNT}
      CHUNK_SIZE: ${CHUNK_SIZE}
      CHUNK_OVERLAP: ${CHUNK_OVERLAP}
      LLM_TYPE: ${LLM_TYPE}
      EMBEDDING_LLM_TYPE: ${EMBEDDING_LLM_TYPE}
      TEMPERATURE: ${TEMPERATURE}
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./data:/data/

